# Generated by Django 5.0.4 on 2024-04-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUserDetails',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiva.basicuserdetails')),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiva.personaluserdetails')),
                ('user_assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiva.userassets')),
            ],
        ),
    ]
