# Generated by Django 5.0.4 on 2024-04-23 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiva', '0002_remove_user_basic_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('useremail', models.CharField(max_length=255, unique=True)),
                ('oauth_provider', models.CharField(max_length=100, null=True)),
                ('oauth_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
