# Generated by Django 5.0.4 on 2024-04-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiva', '0003_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Manushya',
        ),
    ]
